### ISSUE TITLE
Getting MemoryError:Java heap space for Log Files more than 600MB

### ISSUE THREAD

**Issue by sachindere76** [joergeschmann/log-analyzer#1]
11:06:07.079 [main] INFO com.joergeschmann.tools.loganalyzer.App - ================== Log excerpt start ====================
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.joergeschmann.tools.loganalyzer.processing.observer.LogEntry.appendMessageLine(LogEntry.java:63)
	at com.joergeschmann.tools.loganalyzer.processing.observer.AbstractLogEntryObserver.notify(AbstractLogEntryObserver.java:47)
	at 

	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.joergeschmann.tools.loganalyzer.processing.observer.LogEntry.appendMessageLine(LogEntry.java:63)
	at com.joergeschmann.tools.loganalyzer.processing.observer.AbstractLogEntryObserver.notify(AbstractLogEntryObserver.java:47)
	at com.joergeschmann.tools.loganalyzer.processing.observer.LogEntryConsoleAppenderObserver.notify(LogEntryConsoleAppenderObserver.java:17)
	at com.joergeschmann.tools.loganalyzer.processing.AbstractFileProcessor.notifyObservers(AbstractFileProcessor.java:38)
	at com.joergeschmann.tools.loganalyzer.processing.SingleFileProcessor.process(SingleFileProcessor.java:35)
	at com.joergeschmann.tools.loganalyzer.App.run(App.java:62)
	at com.joergeschmann.tools.loganalyzer.App.main(App.java:36)

**Comment by joergeschmann** [comment]
Could you provide more information about this issue? I have just processed a 3GB log file and got no Exception...
What is your heap size for example?
What config/parameters are you using?
Could you share how a log line looks like and how much entries you have?

**Comment by sachindere76** [comment]
Hope this helps. I'm trying to debug the code but it failing at this point. Tried increasing the heap size but then I get the following error which I will send in my next email. Pls help as this tool will be a great asset to my project

**Comment by sachindere76** [comment]
hi joerge,
any update on this?
cheers

**Comment by sachindere76** [comment]
![image](https://cloud.githubusercontent.com/assets/22613494/23595872/4d50f198-0260-11e7-8698-08a915a8ecc5.png)

**Comment by sachindere76** [comment]
![image](https://cloud.githubusercontent.com/assets/22613494/23596078/44949b48-0262-11e7-9daf-ff6a0a0195c2.png)

My Machine confiuration

**Comment by joergeschmann** [comment]
Unless I am not able to reproduce the error it is hard to help...

How did you execute the app?
What parameters did you define, or how does your config.json looks like?
Do you have a repo/fork here on github for further investigation?
How does your log file look like?

**Comment by sachindere76** [comment]
![image](https://cloud.githubusercontent.com/assets/22613494/23600266/b6e2aadc-0280-11e7-9fc4-280c683a3b5e.png)

cant upload the file as it is 64MB. let me try to fork github

**Comment by sachindere76** [comment]
do you need to add me as a member? Not able to push the files

**Comment by sachindere76** [comment]
sorry unfamiliar with github

**Comment by sachindere76** [comment]
https://github.com/sachindere76/log-analyzer.git

**Comment by joergeschmann** [comment]
Could you also describe how a log entry of your log file looks like and what you are trying to achieve?
Do you want to extract certain values or entire log entries with a specific value in a field?

**Comment by sachindere76** [comment]
Hi jeorge 
Let me try to send u tmmrw. Was trying to upload the Log file to GitHub plus Dropbox but it's more than 600MB
I only want to extract certain values ex certain exceptions based on date and time 
I increased the heap size in my machine Using java_opts but no use 
Thanks

**Comment by sachindere76** [comment]
Hi Joerg,
You can download the log file from here
https://www.dropbox.com/s/6ty1vace3wz1nmv/catalina.out?dl=0

Please try it out and see if you can recreate the issue
Thanks

**Comment by joergeschmann** [comment]
Your log file structure is not compatible with the LogEntryParser (https://github.com/sachindere76/log-analyzer/blob/master/src/main/java/com/joergeschmann/tools/loganalyzer/processing/observer/LogEntryParser.java). Currently, you have to implement your own LogEntry and LogEntryParser to correctly parse your log file. I will publish a new release in about a week. With that version it is far more convenient to handle different log file structures.

**Comment by sachindere76** [comment]
Thanks jeorge looking forward for it

**Comment by joergeschmann** [comment]
There is a new version in the dev branch (https://github.com/joergeschmann/log-analyzer/tree/dev). I still need to add some more unit tests and documentation until it is ready for a merger into the master branch. However, you should be able to parse your log file with this version. 

Furthermore, I figured out that your log file does not have a consistent structure, like this part:

14-Nov-2016 16:49:31.193 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8009"]
14-Nov-2016 16:49:31.193 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]
DEBUG 14 Nov 2016 16:49:33 [http-nio-8181-exec-8] [com.ebglobal.vbroker.utils.DBUtil - getConnection() - inside get connecton] 
DEBUG 14 Nov 2016 16:56:43 [http-nio-8181-exec-11] [com.ebglobal.vbroker.utils.DBUtil - getConnection() - inside get connecton] 

The prerequisite for this tool is to have a consistent structure. Otherwise the logic would get too complicated. Therefore, I suggest that you split your large file into multiple files that every slice is consistent.

**Comment by sachindere76** [comment]
Thanks jeorge. Let me go through it when I get back to the office

**Comment by joergeschmann** [comment]
Big files are no problem if the log file has a consistent structure.
